root_path: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/simulations/random_stream_20trials"

patterns_path: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/simulations/spiketrains/random_stream_60/stim.dat"

h5_out:
    file_name: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/simulations/random_stream_20trials/assemblies_simmat.h5"
    prefixes:
        spikes: "spikes"
        assemblies: "assemblies"
        consensus_assemblies: "consensus"
        connectivity: "connectivity"

root_fig_path: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/figures"

preprocessing_protocol:
    t_start: 1000
    t_end: 62000
    bin_size: 10

clustering_methods:
    spikes: "hierarchical"
    assemblies: "hamming"
