root_path: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/simulations/random_stream_20trials"

patterns_fname: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/simulations/spiketrains/random_stream_60.txt"

h5_out:
    file_name: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/simulations/random_stream_20trials/assemblies_spikes.h5"
    prefixes:
        spikes: "spikes"
        assemblies: "assemblies"
        consensus_assemblies: "consensus"
        connectivity: "connectivity"

root_fig_path: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/figures"

preprocessing_protocol:
    t_start: 1000
    t_end: 62000
    bin_size: 10
    threshold_rate: True

clustering_methods:
    spikes: "density_based"
    assemblies: "hamming"
