root_path: "<PATH-TO-SIMULATION-FOLDER>"

input_sequence_fname: "input_spikes/stimulus_stream.txt"
pattern_nodes_fname: "input_spikes/patterns.json"
patterns_edges: {"proj_Thalamocortical_VPM_Source": "VPM__S1nonbarrel_neurons__chemical"}

edge_pop: "S1nonbarrel_neurons__S1nonbarrel_neurons__chemical"

h5_out:
    file_name: "assemblies.h5"
    prefixes:
        spikes: "spikes"
        average_spikes: "average_spikes"
        assemblies: "assemblies"
        consensus_assemblies: "consensus"
        average_assemblies: "average_assemblies"
        connectivity: "connectivity"
        single_cell_features: "single_cell"

root_fig_path: "<PATH-TO-FIGURES-FOLDER>"

preprocessing_protocol:
    node_pop: "S1nonbarrel_neurons"
    target: "Excitatory"
    t_start: 1500
    t_end: 126000
    bin_size: 20

clustering:
    overwrite_n_clusters: {"seed1": 10, "seed47": 9, "seed54": 12, "seed63": 11, "seed80": 9, "seed99": 13}

manuscript_figures:
    assembly_sequences: {"seed19": [1, 3, 7, 9, 6, 10, 2, 4, 8, 5, 0],
                         "consensus": [12, 13, 6, 7, 3, 4, 5, 0, 10, 1, 14, 8, 9, 2, 11],
                         "average": [10, 7, 1, 5, 8, 2, 3, 11, 6, 9, 4, 12, 0]}
