root_path: "<PATH-TO-SIMULATION-FOLDER>"

input_sequence_fname: "input_spikes/stimulus_stream.txt"
pattern_nodes_fname: "input_spikes/patterns.json"
patterns_edges: {"proj_Thalamocortical_VPM_Source": "VPM__S1nonbarrel_neurons__chemical"}

edge_pop: "S1nonbarrel_neurons__S1nonbarrel_neurons__chemical"

h5_out:
    file_name: "assemblies_L23.h5"
    prefixes:
        spikes: "spikes"
        assemblies: "assemblies"

root_fig_path: "<PATH-TO-FIGURES-FOLDER>"

preprocessing_protocol:
    target: "Layer23Excitatory"
    t_start: 1500
    t_end: 126000
    bin_size: 20
    threshold_rate: True

manuscript_figures:
    assembly_sequences: {"seed19": [0, 5, 7, 11, 6, 9, 8, 3, 4, 12, 1, 10, 2, 13]}