root_path: "<PATH-TO-SIMULATION-FOLDER>"

input_sequence_fname: "input_spikes/stimulus_stream.txt"
pattern_nodes_fname: "input_spikes/patterns.json"
patterns_edges: {"proj_Thalamocortical_VPM_Source": "VPM__S1nonbarrel_neurons__chemical"}

edge_pop: "S1nonbarrel_neurons__S1nonbarrel_neurons__chemical"

h5_out:
    file_name: "assemblies.h5"
    prefixes:
        spikes: "spikes"
        average_spikes: "average_spikes"
        assemblies: "assemblies"
        consensus_assemblies: "consensus"
        average_assemblies: "average_assemblies"
        connectivity: "connectivity"
        single_cell_features: "single_cell"

root_fig_path: "<PATH-TO-FIGURES-FOLDER>"

preprocessing_protocol:
    node_pop: "S1nonbarrel_neurons"
    target: "Excitatory"
    t_start: 1500
    t_end: 122000
    bin_size: 20
    surr_rate_method: "keep_sc_rate"

manuscript_figures:
    assembly_sequences: {"consensus": [6, 7, 3, 4, 8, 2, 1, 0, 5]}
