root_path: "<PATH-TO-SIMULATION-FOLDER>"

input_sequence_fname: "input_spikes/stimulus_stream.txt"
pattern_nodes_fname: "input_spikes/patterns.json"
patterns_edges: {"proj_Thalamocortical_VPM_Source": "VPM__S1nonbarrel_neurons__chemical"}

edge_pop: "S1nonbarrel_neurons__S1nonbarrel_neurons__chemical"

h5_out:
    file_name: "assemblies.h5"
    prefixes:
        spikes: "spikes"
        assemblies: "assemblies"
        connectivity: "connectivity"

root_fig_path: "<PATH-TO-FIGURES-FOLDER>"

preprocessing_protocol:
    node_pop: "S1nonbarrel_neurons"
    target: "Excitatory"
    t_start: 1500
    t_end: 602000
    bin_size: 20
    surr_rate_method: "keep_sc_rate"

clustering:
    synapses:
        cross_assemblies: {"seed1": {0: [3, 5], 1: [0], 2: [0, 4, 6, 8], 4: [7, 9, 10, 11], 5: [12], 6: [13, 14]}}
        target_range: 10
        min_nsyns: 10
        n_neurons_sample: 10

manuscript_figures:
    assembly_sequences: {"seed1": [9, 7, 2, 10, 6, 4, 3, 5, 8, 11, 0, 1]}
