root_path: "/gpfs/bbp.cscs.ch/project/proj96/scratch/home/ecker/simulations/b2594590-20b4-40ff-9c91-1a7382465af4"

patterns_fname: "input_spikes/stimulus_stream__start2000__end181501__rate2__seed12.txt"

h5_out:
    file_name: "assemblies.h5"
    prefixes:
        spikes: "spikes"
        assemblies: "assemblies"
        consensus_assemblies: "consensus"
        connectivity: "connectivity"
        single_cell_features: "single_cell"

root_fig_path: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/figures/v7_assemblies"

preprocessing_protocol:
    target: "hex_O1"
    t_start: 1500
    t_end: 182500
    bin_size: 20
    threshold_rate: True

clustering:
    spikes:
        method: "hierarchical"
        core_cell_th_pct: 99
    assemblies:
        method: "hierarchical"
    synapses:
        target_range: 5
        min_nsyns: 5
        n_neurons_sample: 10
