root_path: "/gpfs/bbp.cscs.ch/project/proj96/scratch/home/ecker/simulations/5b1420ca-dd31-4def-96d6-46fe99d20dcc"

patterns_fname: "input_spikes/stimulus_stream__start2000__end602001__rate2__seed12.txt"

h5_out:
    file_name: "assemblies.h5"
    prefixes:
        spikes: "spikes"
        assemblies: "assemblies"
        consensus_assemblies: "consensus"
        connectivity: "connectivity"
        single_cell_features: "single_cell"

root_fig_path: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/figures/v7_assemblies"

preprocessing_protocol:
    target: "hex_O1"
    t_start: 1500
    t_end: 602500
    t_chunks: 10
    bin_size: 20
    threshold_rate: True

clustering:
    spikes:
        method: "hierarchical"
    assemblies:
        method: "hierarchical"
