root_path: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/simulations/random_stream_20trials_set1"

patterns_fname: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/simulations/spiketrains/random_stream_60_2sets.txt"

h5_out:
    file_name: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/simulations/random_stream_20trials_set1/assemblies.h5"
    prefixes:
        spikes: "spikes"
        assemblies: "assemblies"
        consensus_assemblies: "consensus"
        connectivity: "connectivity"

root_fig_path: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/figures"

preprocessing_protocol:
    target: "mc2_Column"
    t_start: 2000
    t_start_exception: 4000
    seeds_exception: [76321, 412653, 820074]
    ignore_seeds: [756873]
    t_end: 63000
    bin_size: 10
    threshold_rate: True

clustering_methods:
    spikes: "hierarchical"
    assemblies: "hierarchical"
